disabled_rules:
  - multiple_closures_with_trailing_closure
  - nesting
  - switch_case_on_newline
opt_in_rules:
  - accessibility_label_for_image
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition
analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import
excluded:
  - Build
  - DerivedData
  - Pods
  - "**/Generated"
  - "**/Mocks"
  - "**/Preview Content"

# Default Rules
closing_brace:
  severity: error
closure_parameter_position:
  severity: error
colon:
  severity: error  
comma:
  severity: error
computed_accessors_order:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  ignores_case_statements: true
deployment_target:
  severity: error
duplicated_key_in_dictionary_literal:
  severity: error
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true
function_body_length:
  warning: 30
  error: 40
identifier_name:
  min_length: 2
  max_length: 60
  severity: error
large_tuple:
  warning: 4
  error: 6
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
line_length:
  ignores_urls: true
  warning: 150
mark:
  severity: error
no_space_in_method_call:
  severity: error
opening_brace:
  severity: error
operator_whitespace:
  severity: error
orphaned_doc_comment:
  severity: error
private_unit_test:
  severity: error
protocol_property_accessors_order:
  severity: error
reduce_boolean:
  severity: error
redundant_discardable_let:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
shorthand_operator:
  severity: error
statement_position:
  severity: error
switch_case_alignment:
  severity: error
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_name:
  max_length: 50
unavailable_condition:
  severity: error
unneeded_break_in_switch:
  severity: error
unused_closure_parameter:
  severity: error
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: error
unused_optional_binding:
  severity: error
unused_setter_value:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error

# Opt-In Rules
accessibility_label_for_image:
  severity: error
attributes:
  severity: error
balanced_xctest_lifecycle:
  severity: error
closure_body_length:
  warning: 100
closure_end_indentation:
  severity: error
closure_spacing:
  severity: error
collection_alignment:
  severity: error
contains_over_filter_count:
  severity: error
contains_over_filter_is_empty:
  severity: error
contains_over_first_not_nil:
  severity: error
contains_over_range_nil_comparison:
  severity: error
discarded_notification_center_observer:
  severity: error
discouraged_none_name:
  severity: error
discouraged_object_literal:
  severity: error
empty_collection_literal:
  severity: error
empty_count:
  severity: warning
empty_string:
  severity: error
empty_xctest_method:
  severity: error
explicit_init:
  severity: error
extension_access_modifier:
  severity: error
file_header:
  severity: error
file_name_no_space:
  severity: error
file_types_order:
  severity: error
first_where:
  severity: error
flatmap_over_map_reduce:
  severity: error
force_unwrapping:
  severity: error
ibinspectable_in_extension:
  severity: error
identical_operands:
  severity: error
implicit_return:
  severity: warning
implicitly_unwrapped_optional:
  severity: error
indentation_width:
  include_comments: false
  severity: error
joined_default_parameter:
  severity: error
last_where:
  severity: error
legacy_multiple:
  severity: error
let_var_whitespace:
  severity: error
literal_expression_end_indentation:
  severity: error
lower_acl_than_parent:
  severity: error
modifier_order:
  severity: error
multiline_arguments:
  severity: error
  only_enforce_after_first_closure_on_first_line: true
multiline_arguments_brackets:
  severity: error
multiline_function_chains:
  severity: error
multiline_literal_brackets:
  severity: error
multiline_parameters:
  severity: error
multiline_parameters_brackets:
  severity: error
operator_usage_whitespace:
  severity: error
overridden_super_call:
  severity: error
pattern_matching_keywords:
  severity: error
prefer_self_in_static_references:
  severity: error
prefer_self_type_over_type_of_self:
  severity: error
prefer_zero_over_explicit_init:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
private_subject:
  severity: error
prohibited_super_call:
  severity: error
reduce_into:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_type_annotation:
  severity: error
return_value_from_void_function:
  severity: error
sorted_first_last:
  severity: error
sorted_imports:
  severity: error
static_operator:
  severity: error
strong_iboutlet:
  severity: error
toggle_bool:
  severity: error
type_contents_order:
  severity: error
unavailable_function:
  severity: error
unneeded_parentheses_in_closure_argument:
  severity: error
unowned_variable_capture:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace_closing_braces:
  severity: error
vertical_whitespace_opening_braces:
  severity: error
weak_delegate:
  severity: error
xct_specific_matcher:
  severity: error
yoda_condition:
  severity: error
# Analyzer Rules
capture_variable:
  severity: error
unused_declaration:
  severity: error
unused_import:
  severity: error
