#!/bin/bash

# https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

PATH=`echo ~`/.rbenv/shims:$PATH
cd $DIR/..
bundle exec ruby hooks/xcodeproj.rb

git add $DIR/../Movies/Movies.xcodeproj
git add $DIR/../Common/Common.xcodeproj
git add $DIR/../UI/UI.xcodeproj
git add $DIR/../Utils/Utils.xcodeproj
