name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build-and-test:
    
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true # runs 'bundle install' and caches installed
      
    - name: Pod install
      run: bundle exec pod install
        
    - name: Build
      run: xcodebuild clean build -workspace Movies.xcworkspace -scheme Movies CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Run tests
      run: bundle exec fastlane test
